name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.event_name != 'push' || !startsWith(github.event.head_commit.message, 'Bump version')
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: Win32
            name: x86
          - arch: x64
            name: x86_64
          - arch: ARM64
            name: arm64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Configure CMake
      run: >
        cmake -B build -G "Visual Studio 17 2022" -A ${{ matrix.arch }}

    - name: Build
      run: cmake --build build --config Release

    - name: Set Release Version
      id: version
      shell: pwsh
      run: |
        $VERSION = if ("${{ github.event_name }}" -eq "release") { "${{ github.event.release.tag_name }}" } else { "latest" }
        "version=$VERSION" >> $env:GITHUB_OUTPUT

    - name: Prepare and Zip Artifacts
      shell: pwsh
      run: |
        $DIR = "wasapi-bridge-${{ steps.version.outputs.version }}-${{ matrix.name }}"
        $ZIP = "${DIR}.zip"
        New-Item -ItemType Directory -Path $DIR | Out-Null
        Copy-Item build\Release\wasapi-bridge.exe -Destination $DIR
        Copy-Item config.example.ini -Destination (Join-Path $DIR "config.ini")
        Copy-Item LICENSE -Destination $DIR
        Compress-Archive -Path $DIR -DestinationPath $ZIP

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: wasapi-bridge-${{ steps.version.outputs.version }}-${{ matrix.name }}
        path: wasapi-bridge-${{ steps.version.outputs.version }}-${{ matrix.name }}

    - name: Upload to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v3
      with:
        files: wasapi-bridge-${{ steps.version.outputs.version }}-${{ matrix.name }}.zip
